# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bf20bf25d757e0e1e916ac7d38691f8e02f10a5e791d80bfffc4a665377d239f426259966c7d949b8525f2300449bb2ff44771dff6fc4407da7ca1be0d03afe

test:
  secret_key_base: 6bee8163038b059bff1769193a4c92a7832879e1be226926badad770c9a387e275ed82ac8a2d367e577e5f535dc123d38eb9fc83bd4596cc952e5bcfaed26aa0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
